#!/usr/bin/env bash
# Ignore shellcheck SC2086

domain=$1
subdomain=$2

get_record() {
    sub=$1
    result=$(dig $sub.$domain | grep -A1 "ANSWER SECTION:" | tail -n1)

    record_type=$(echo $result | awk '{print $4}')
    destination=$(echo $result | awk '{print $5}')

    echo "The subdomain $sub is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]
then
    for sub in www lb-01 web-01 web-02
    do
        get_record $sub
    done
else
    get_record $subdomain
fi
